# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-01-11 09:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rend', '0002_project'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='image_likes',
        ),
        migrations.RemoveField(
            model_name='image',
            name='imageuploader_profile',
        ),
        migrations.AlterField(
            model_name='comments',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='rend.Project'),
        ),
        migrations.AlterField(
            model_name='likes',
            name='liked_post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='rend.Project'),
        ),
        migrations.DeleteModel(
            name='Image',
        ),
    ]
